# Generated by Django 3.1.6 on 2021-02-11 12:03

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Photos')),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselAdvImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('Home_carousel1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_carousel2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_carousel3', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_top1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_top2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle3', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_Bottom_long', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_Bottom_Short', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel1', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel2', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel3', models.ImageField(blank=True, upload_to='Photos')),
                ('Become_Seller_Image', models.ImageField(blank=True, upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='Photos')),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Photos')),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Number', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('order_note', models.TextField(max_length=70, null=True)),
                ('payment', models.CharField(choices=[('Cash On Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash')], max_length=20, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Refund in Process', 'Refund in Process'), ('Refunded', 'Refunded')], max_length=20, null=True)),
                ('OrderTotal', models.FloatField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='Photos')),
                ('favIcon', models.ImageField(blank=True, upload_to='Photos')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('privacyPolicy', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('returnPolicy', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('paymentProcess', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('isActive', models.BooleanField(default=False, max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('charge', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('address', models.TextField(null=True)),
                ('image', models.ImageField(default='avatar.png', upload_to='Photos')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('discountPrice', models.FloatField(blank=True, null=True, verbose_name='Discount Price')),
                ('label', models.CharField(choices=[('Sale', 'Sale'), ('New', 'New'), ('Flash Sale', 'Flash Sale'), ('Promotion', 'Promotion')], max_length=30)),
                ('stockQuantity', models.IntegerField(default=1, verbose_name='Stock Quantity')),
                ('shortDescription', ckeditor_uploader.fields.RichTextUploadingField()),
                ('longDescirption', ckeditor_uploader.fields.RichTextUploadingField()),
                ('mainImage', models.ImageField(upload_to='Photos', verbose_name='Main Image')),
                ('altImageOne', models.ImageField(upload_to='Photos', verbose_name='Gallery Image One')),
                ('altImageTwo', models.ImageField(upload_to='Photos', verbose_name='Gallery Image Two')),
                ('isactive', models.BooleanField(default=False, verbose_name='Is Active')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOrdered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
