# Generated by Django 3.1.4 on 2021-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselAdvImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('Home_carousel1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_carousel2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_carousel3', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_top1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_top2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle1', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle2', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_middle3', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_Bottom_long', models.ImageField(blank=True, upload_to='Photos')),
                ('Home_Adv_Bottom_Short', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel1', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel2', models.ImageField(blank=True, upload_to='Photos')),
                ('Shop_carousel3', models.ImageField(blank=True, upload_to='Photos')),
                ('Become_Seller_Image', models.ImageField(blank=True, upload_to='Photos')),
            ],
        ),
    ]
