# Generated by Django 2.2.4 on 2020-12-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Categories',
        ),
    ]
