# Generated by Django 3.1.4 on 2021-02-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
        ('core', '0002_remove_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_simple_coupons.coupon'),
        ),
    ]
