# Generated by Django 2.2.4 on 2020-12-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201217_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('discountPrice', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(choices=[('S', 'Sale'), ('N', 'New'), ('Fs', 'Flash Sale'), ('P', 'Promotion')], max_length=30)),
                ('stockQuantity', models.CharField(max_length=50)),
                ('shortDescription', models.TextField()),
                ('longDescirption', models.TextField()),
                ('mainImage', models.ImageField(upload_to='Photos')),
                ('altImageOne', models.ImageField(upload_to='Photos')),
                ('altImageTwo', models.ImageField(upload_to='Photos')),
                ('isactive', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Brands')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories')),
            ],
        ),
    ]
