# Generated by Django 2.2.4 on 2020-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201217_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discountPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Price'),
        ),
    ]
