# Generated by Django 2.2.4 on 2020-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201217_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='altImageOne',
            field=models.ImageField(upload_to='Photos', verbose_name='Gallery Image One'),
        ),
        migrations.AlterField(
            model_name='products',
            name='altImageTwo',
            field=models.ImageField(upload_to='Photos', verbose_name='Gallery Image Two'),
        ),
        migrations.AlterField(
            model_name='products',
            name='isactive',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='products',
            name='longDescirption',
            field=models.TextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='mainImage',
            field=models.ImageField(upload_to='Photos', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='shortDescription',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stockQuantity',
            field=models.CharField(max_length=50, verbose_name='Stock Quantity'),
        ),
    ]
