# Generated by Django 2.2.4 on 2020-12-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201217_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='label',
            field=models.CharField(choices=[('Sale', 'Sale'), ('New', 'New'), ('Flash Sale', 'Flash Sale'), ('Promotion', 'Promotion')], max_length=30),
        ),
    ]
