# Generated by Django 2.2.4 on 2020-12-27 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201219_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('ordered_date', models.DateTimeField()),
                ('isOrdered', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('order_note', models.TextField(max_length=70)),
                ('payment', models.CharField(choices=[('Sale', 'Sale'), ('New', 'New'), ('Flash Sale', 'Flash Sale'), ('Promotion', 'Promotion')], max_length=20)),
                ('order_status', models.CharField(choices=[('Pr', 'Processing'), ('Pen', 'Pending'), ('Can', 'Canceled'), ('Dlv', 'Delivered'), ('Ref', 'Refund in Process'), ('Refd', 'Refunded')], max_length=20)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Coupon')),
                ('items', models.ManyToManyField(to='core.CartProducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
