# Generated by Django 2.2.4 on 2020-12-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartproducts_coupon_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='ordered',
            new_name='isOrdered',
        ),
    ]
