# Generated by Django 3.1.4 on 2020-12-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201227_1440'),
        ('core', '0012_cartproducts'),
    ]

    operations = [
    ]
