# Generated by Django 3.1.4 on 2020-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20201228_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='isOrdered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Bk', 'Bkash')], max_length=20),
        ),
    ]
