# Generated by Django 3.1.4 on 2020-12-28 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201228_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OrderAmount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
