# Generated by Django 3.1.4 on 2020-12-29 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
