# Generated by Django 3.1.4 on 2020-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
