# Generated by Django 3.1.4 on 2020-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201229_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/avatar.png', upload_to='Photos'),
        ),
    ]
