# Generated by Django 3.1.4 on 2020-12-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/avatar.webp', upload_to='Photos'),
        ),
    ]
