# Generated by Django 3.1.4 on 2020-12-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201231_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='Photos'),
        ),
    ]
