# Generated by Django 3.1.4 on 2021-01-03 06:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210103_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='shortDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
