# Generated by Django 3.1.4 on 2021-01-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210104_1255'),
        ('core', '0033_auto_20210104_1349'),
    ]

    operations = [
    ]
