# Generated by Django 3.1.4 on 2021-01-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrderAmount',
            new_name='OrderTotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isOrdered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
