# Generated by Django 3.1.4 on 2021-01-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210104_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Refund in Process', 'Refund in Process'), ('Refunded', 'Refunded')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash')], max_length=20),
        ),
    ]
