# Generated by Django 3.1.4 on 2021-01-24 05:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210124_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='longDescirption',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='shortDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
