# Generated by Django 3.1.4 on 2021-01-25 08:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210125_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='paymentProcess',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
