# Generated by Django 3.1.4 on 2021-01-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210125_1156'),
        ('core', '0046_settings_paymentprocess'),
    ]

    operations = [
    ]
